name: 'dbt_learning'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Database/schema/materialization configs live in:
#   - seeds/schema.yml
#   - models/staging/schema.yml
#   - models/marts/schema.yml
